# Generated by Django 4.1.7 on 2023-05-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_usertask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodule',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
